"""build a single sql file for testing sql/00_control + sql/03_gold on a real,
local sql server instance (ssms / sql express) instead of fabric warehouse.

only difference from the real files: "not enforced" is stripped from every
primary key, because that's a fabric/synapse-only constraint option - real
sql server doesn't parse it at all. everything else is untouched, so this is
testing the actual ddl we ship, not a rewrite of it.

known local-only gap: 90_util_numbers.sql uses GENERATE_SERIES, which needs
sql server 2022+. an older local instance fails that one batch and
ctl.util_numbers stays empty - gold.usp_populate_dim_date then still "succeeds"
but populates only its -1 unknown-member row. this only affects local testing;
GENERATE_SERIES is confirmed working on the real fabric warehouse.

not committed to git - regenerate any time with:
    python tools/build_local_test_sql.py
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "tools" / "_local_test_setup.sql"

# order matters: ctl schema/tables before gold, and within each folder the
# existing NN_ prefixes are already the right order. seed files are skipped -
# they insert into ctl.source_config / ctl.dq_rule referencing tables that
# only make sense once data/ has been generated; run them separately if wanted.
FILES = [
    "sql/00_control/00_create_schemas.sql",
    "sql/00_control/10_source_config.sql",
    "sql/00_control/20_pipeline_run_log.sql",
    "sql/00_control/30_dq_framework.sql",
    "sql/00_control/40_dq_runner.sql",
    "sql/00_control/50_vin_reference.sql",
    "sql/00_control/80_logging_procs.sql",
    "sql/00_control/90_util_numbers.sql",
    "sql/03_gold/00_dim_date.sql",
    "sql/03_gold/10_dimensions.sql",
    "sql/03_gold/20_facts.sql",
    "sql/03_gold/30_scd2_pattern.sql",
    "sql/03_gold/40_dim_loads.sql",
    "sql/03_gold/50_fact_loads.sql",
    "sql/03_gold/60_aggregates.sql",
    "sql/03_gold/70_orchestration.sql",
]


def main() -> None:
    parts = [
        "-- generated by tools/build_local_test_sql.py - do not edit by hand.",
        "-- same ddl as sql/00_control + sql/03_gold, with 'NOT ENFORCED' removed",
        "-- so it runs on a real (non-fabric) sql server. run this in ssms against",
        "-- a fresh database, e.g.: CREATE DATABASE MihenkTest; then USE MihenkTest;",
        "",
        "-- vw_vin_check_digit and the backfill/load procedures reference",
        "-- silver.* and bronze.* tables that don't exist locally (those are",
        "-- fabric lakehouse/delta objects). the views and procedures still get",
        "-- CREATEd fine - sql server defers name resolution - they just can't be",
        "-- EXECuted until those tables exist. gold.usp_populate_dim_date has no",
        "-- such dependency and can be run immediately.",
        "",
    ]

    total_stripped = 0
    for rel in FILES:
        text = (REPO / rel).read_text(encoding="utf-8")
        stripped, n = re.subn(r"\s+NOT ENFORCED", "", text)
        total_stripped += n
        parts.append(f"-- ===== {rel} =====")
        parts.append(stripped)
        parts.append("")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}  ({total_stripped} 'NOT ENFORCED' occurrences removed)")


if __name__ == "__main__":
    main()
