"""sql/00_control + sql/03_gold'u fabric warehouse yerine gerçek, yerel bir sql
server örneğinde (ssms / sql express) test etmek için tek bir sql dosyası kur.

gerçek dosyalardan tek farkı: her primary key'den "not enforced" çıkarılıyor,
çünkü bu sadece fabric/synapse'e özgü bir kısıt seçeneği - gerçek sql server
bunu hiç ayrıştıramıyor. geri kalan her şey olduğu gibi, yani teslim ettiğimiz
ddl'in kendisi test ediliyor, yeniden yazılmış hâli değil.

bilinen yerel eksik: 90_util_numbers.sql GENERATE_SERIES kullanıyor, bu da sql
server 2022+ istiyor. daha eski bir yerel örnek o tek batch'te hata verir ve
ctl.util_numbers boş kalır - gold.usp_populate_dim_date yine "başarılı" olur ama
sadece -1 bilinmiyor üyesini doldurur. bu sadece yerel testi etkiler;
GENERATE_SERIES gerçek fabric warehouse'ta çalıştığı doğrulandı.

git'e girmiyor - istediğin zaman şununla yeniden üret:
    python tools/build_local_test_sql.py
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "tools" / "_local_test_setup.sql"

# sıra önemli: önce ctl şema/tabloları sonra gold, her klasörün içinde de mevcut
# NN_ önekleri zaten doğru sırayı veriyor. seed dosyaları atlanıyor - onlar
# ctl.source_config / ctl.dq_rule'a, ancak data/ üretildikten sonra anlamlı olan
# tablolara referans vererek insert atıyor; istenirse ayrıca çalıştırılır.
FILES = [
    "sql/00_control/00_create_schemas.sql",
    "sql/00_control/10_source_config.sql",
    "sql/00_control/20_pipeline_run_log.sql",
    "sql/00_control/30_dq_framework.sql",
    "sql/00_control/40_dq_runner.sql",
    "sql/00_control/50_vin_reference.sql",
    "sql/00_control/80_logging_procs.sql",
    "sql/00_control/90_util_numbers.sql",
    "sql/03_gold/00_dim_date.sql",
    "sql/03_gold/10_dimensions.sql",
    "sql/03_gold/20_facts.sql",
    "sql/03_gold/30_scd2_pattern.sql",
    "sql/03_gold/40_dim_loads.sql",
    "sql/03_gold/50_fact_loads.sql",
    "sql/03_gold/60_aggregates.sql",
    "sql/03_gold/70_orchestration.sql",
]


def main() -> None:
    parts = [
        "-- generated by tools/build_local_test_sql.py - do not edit by hand.",
        "-- same ddl as sql/00_control + sql/03_gold, with 'NOT ENFORCED' removed",
        "-- so it runs on a real (non-fabric) sql server. run this in ssms against",
        "-- a fresh database, e.g.: CREATE DATABASE MihenkTest; then USE MihenkTest;",
        "",
        "-- vw_vin_check_digit and the backfill/load procedures reference",
        "-- silver.* and bronze.* tables that don't exist locally (those are",
        "-- fabric lakehouse/delta objects). the views and procedures still get",
        "-- CREATEd fine - sql server defers name resolution - they just can't be",
        "-- EXECuted until those tables exist. gold.usp_populate_dim_date has no",
        "-- such dependency and can be run immediately.",
        "",
    ]

    total_stripped = 0
    for rel in FILES:
        text = (REPO / rel).read_text(encoding="utf-8")
        stripped, n = re.subn(r"\s+NOT ENFORCED", "", text)
        total_stripped += n
        parts.append(f"-- ===== {rel} =====")
        parts.append(stripped)
        parts.append("")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}  ({total_stripped} 'NOT ENFORCED' occurrences removed)")


if __name__ == "__main__":
    main()
